Test begin
qs_new(), qs_elm_new()
  qs_foreach():
  qs_top(): NULL
qs_push()
  -->Iteration 0
  qs_foreach(): a
  qs_top(): a
  qs_down(qs_top()): NULL
  -->Iteration 1
  qs_foreach(): b a
  qs_top(): b
  qs_down(qs_top()): a
  -->Iteration 2
  qs_foreach(): c b a
  qs_top(): c
  qs_down(qs_top()): b
  -->Iteration 3
  qs_foreach(): d c b a
  qs_top(): d
  qs_down(qs_top()): c
  -->Iteration 4
  qs_foreach(): e d c b a
  qs_top(): e
  qs_down(qs_top()): d
  -->Iteration 5
  qs_foreach(): f e d c b a
  qs_top(): f
  qs_down(qs_top()): e
  -->Iteration 6
  qs_foreach(): g f e d c b a
  qs_top(): g
  qs_down(qs_top()): f
  -->Iteration 7
  qs_foreach(): h g f e d c b a
  qs_top(): h
  qs_down(qs_top()): g
qs_pop()
  -->Iteration 0
  qs_foreach(): g f e d c b a
  qs_top(): g
  qs_down(qs_top()): f
  -->Iteration 1
  qs_foreach(): f e d c b a
  qs_top(): f
  qs_down(qs_top()): e
  -->Iteration 2
  qs_foreach(): e d c b a
  qs_top(): e
  qs_down(qs_top()): d
  -->Iteration 3
  qs_foreach(): d c b a
  qs_top(): d
  qs_down(qs_top()): c
  -->Iteration 4
  qs_foreach(): c b a
  qs_top(): c
  qs_down(qs_top()): b
  -->Iteration 5
  qs_foreach(): b a
  qs_top(): b
  qs_down(qs_top()): a
  -->Iteration 6
  qs_foreach(): a
  qs_top(): a
  qs_down(qs_top()): NULL
  -->Iteration 7
  qs_foreach():
  qs_top(): NULL
qs_under_push()
  -->Iteration 1
  qs_foreach(): a b
  qs_top(): a
  qs_down(qs_top()): b
  -->Iteration 2
  qs_foreach(): a c b
  qs_top(): a
  qs_down(qs_top()): c
  -->Iteration 3
  qs_foreach(): a d c b
  qs_top(): a
  qs_down(qs_top()): d
  -->Iteration 4
  qs_foreach(): a e d c b
  qs_top(): a
  qs_down(qs_top()): e
  -->Iteration 5
  qs_foreach(): a f e d c b
  qs_top(): a
  qs_down(qs_top()): f
  -->Iteration 6
  qs_foreach(): a g f e d c b
  qs_top(): a
  qs_down(qs_top()): g
  -->Iteration 7
  qs_foreach(): a h g f e d c b
  qs_top(): a
  qs_down(qs_top()): h
qs_pop()
  -->Iteration 0
  qs_foreach(): h g f e d c b
  qs_top(): h
  qs_down(qs_top()): g
  -->Iteration 1
  qs_foreach(): g f e d c b
  qs_top(): g
  qs_down(qs_top()): f
  -->Iteration 2
  qs_foreach(): f e d c b
  qs_top(): f
  qs_down(qs_top()): e
  -->Iteration 3
  qs_foreach(): e d c b
  qs_top(): e
  qs_down(qs_top()): d
  -->Iteration 4
  qs_foreach(): d c b
  qs_top(): d
  qs_down(qs_top()): c
  -->Iteration 5
  qs_foreach(): c b
  qs_top(): c
  qs_down(qs_top()): b
  -->Iteration 6
  qs_foreach(): b
  qs_top(): b
  qs_down(qs_top()): NULL
  -->Iteration 7
  qs_foreach():
  qs_top(): NULL
Test end
