/* -*- mode: c ; c-file-style: "canonware-c-style" -*-
 * This file is automatically generated.
 ******************************************************************************
 *
 * <Copyright = jasone>
 * <License>
 *
 ******************************************************************************
 *
 * Version: Onyx <Version = onyx>
 *
 ******************************************************************************/

#include "libonyx/libonyx.h"

void
nxo_p_thread_nxcode(cw_nxo_t *a_thread)
{
    cw_onyx_code(a_thread, "{dict begin $userdict currentdict dstack dup sbdup dup spop begin pop $threaddict currentdict def def $currenterror < $newerror false $errorname `' $estack stack $istack stack $ostack stack $dstack stack $line 1 $column 0 > def $errordict < $stop $stop load $handleerror {$currenterror load begin $errorname load $syntaxerror eq {stderr dup `At line ' {write} {} until dup $line load cvs {write} {} until dup `, column ' {write} {} until dup $column load cvs {write} {} until `: ' {write} {} until} if stderr dup `Error ' {write} {} until dup $errorname load 1 sprints {write} {} until dup `\nostack: ' {write} {} until dup $ostack load 1 sprints {write} {} until dup `\ndstack: ' {write} {} until dup $dstack load 1 sprints {write} {} until `\n' {write} {} until $estack load scount 1 sub dup 0 gt {stderr dup `estack/istack trace (0..' {write} {} until 1 idup cvs stderr exch {write} {} until `):\n' {write} {} until} if 0 1 dn {dup cvs stderr exch {write} {} until dup $estack load dup dn sidup spop dup type $arraytype eq {`: {\n' stderr exch {write} {} until dup length 1 sub 0 1 dn {2 idup $istack load dup dn sidup spop 1 idup eq {dup < $w 3 > outputs stderr exch {write} {} until `:--> '} {`\t'} ifelse stderr exch {write} {} until 1 idup exch get 1 sprints stderr exch {write} {} until stderr `\n' {write} {} until} for stderr `}\n' {write} {} until pop} {stderr `:\t' {write} {} until 1 sprints stderr exch {write} {} until stderr `\n' {write} {} until} ifelse pop} for end flush} bind > def end}eval");
}
