Test begin
main(): i == 0
main(): _CW_XEPV_CODE
main(): _CW_XEPV_FINALLY
main(): i == 1
main(): _CW_XEPV_CODE
main(): _CW_XEPV_FINALLY
main(): i == 2
main(): _CW_XEPV_CODE
main(): _CW_XEPV_FOO
main(): _CW_XEPV_BAR
main(): _CW_XEPV_FINALLY
main(): i == 3
main(): _CW_XEPV_CODE
main(): _CW_XEPV_BIZ
main(): _CW_XEPV_FINALLY
main(): i == 4
main(): _CW_XEPV_CODE
main(): _CW_XEPV_FINALLY
main(): i == 5
main(): _CW_XEPV_CODE
func_b(): _CW_XEPV_CODE
func_b(): _CW_XEPV_BIZ
main(): _CW_XEPV_FINALLY
main(): i == 6
main(): _CW_XEPV_CODE
func_c(): _CW_XEPV_CODE
func_c(): _CW_XEPV_FINALLY
main(): _CW_XEPV_BIZ
main(): _CW_XEPV_FINALLY
main(): i == 7
main(): _CW_XEPV_CODE
main(): _CW_XEPV_BAZ
main(): _CW_XEPV_CODE
main(): _CW_XEPV_BANG
main(): _CW_XEPV_FINALLY
main(): i == 9
main(): _CW_XEPV_CODE
main(): _CW_XEPV_BAM
main(): _CW_XEPV_FINALLY
main(): i == 10
main(): _CW_XEPV_CODE
main(): _CW_XEPV_FINALLY
Test end
