#!/usr/bin/perl
#-*-mode:perl-*-
#############################################################################
#
# Copyright (C) 1998-1999 Jason Evans.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice(s), this list of conditions and the following disclaimer as
#    the first lines of this file unmodified other than the possible 
#    addition of one or more copyright notices.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice(s), this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER(S) ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.
#
#############################################################################
#
# <<< Description >>>
#
# This script does all the necessary work to create a snapshot release of a 
# source tree that is under cvs control.  It also does string substitution 
# for certain tags, such as <Copyright = "Author">, <License>, and <Version>.
#
#############################################################################

use Cwd; # For pwd().
use File::Find; # For find().
use FileHandle; # For file manipulation.
use Getopt::Long;

# Add values to the %COPYRIGHT associative array as shown below to add 
# copyright holder tag keys.  This allows substition of tags that look like:
#
# <Copyright = jasone>
#
$COPYRIGHT{"jasone", 0}
= "Copyright (C) 1996-1999 Jason Evans <jasone\@canonware.com>.";
$COPYRIGHT{"jasone", 1}
= "All rights reserved.";

# XXX The contents of @LICENSE are substituted for tags that look like:
#
# <License>
#
@LICENSE = 
(
 '',
 'Redistribution and use in source and binary forms, with or without',
 'modification, are permitted provided that the following conditions',
 'are met:',
 '1. Redistributions of source code must retain the above copyright',
 '   notice(s), this list of conditions and the following disclaimer as',
 '   the first lines of this file unmodified other than the possible',
 '   addition of one or more copyright notices.',
 '2. Redistributions in binary form must reproduce the above copyright',
 '   notice(s), this list of conditions and the following disclaimer in',
 '   the documentation and/or other materials provided with the',
 '   distribution.',
 '',
 "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER(S) ``AS IS'' AND ANY",
 'EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE',
 'IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR',
 'PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER(S) BE',
 'LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR',
 'CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF',
 'SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR',
 'BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,',
 'WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE',
 'OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,',
 'EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.'
 );

#
# Parse command-line arguments.
#
Getopt::Long::config("bundling"); # Allow -hv rather than forcing -h -v.

$opt_retval = 
    &GetOptions("h|help" => \$opt_help,
		"n|noact" => \$opt_noact,
		"v|verbose" => \$opt_verbose,
		"t|tag=s" => \$opt_tag,
		"d|dir=s" => \$opt_subdir
		);

if (($#ARGV >= 0) 
    || ($opt_retval == 0)
    || (!defined($opt_tag))
    || (!defined($opt_subdir))
    || ($opt_help)
    )
{
    &print_usage;
    exit(1);
}
if ($opt_tag =~ /^[^A-Za-z]/)
{
    print STDERR "Error: tag must start with a letter\n";
    &print_usage;
    exit(1);
}
while ($opt_subdir =~ /\/$/)
{
    if ($opt_verbose)
    {
	print STDERR "Discarding trailing '/' from \"$opt_subdir\"\n";
    }
    chop $opt_subdir;
}
if ($opt_subdir =~ /\//)
{
    $opt_subdir =~ /(.+)\/([-A-Za-z_0-9]+)$/;
    $dirpath = $1;
    $subdir = $2;
}
else
{
    $dirpath = ".";
    $subdir = $opt_subdir;
}

if ($opt_verbose)
{
    print STDERR "Path to directory: \"$dirpath\"\n";
    print STDERR "Directory: \"$subdir\"\n";
}

if ($opt_verbose)
{
    print STDERR "cvs tag $opt_tag $dirpath/$subdir\n";
}
unless ($opt_noact)
{
    `cvs tag $opt_tag $dirpath/$subdir`;
}

if ($opt_verbose)
{
    print STDERR 
	"cvs export -r $opt_tag -d $subdir\_$opt_tag $dirpath/$subdir\n";
}
unless ($opt_noact)
{
    `cvs export -r $opt_tag -d $subdir\_$opt_tag $dirpath/$subdir`;
}

# Find all the files that need the copyright tag expanded.
if ($opt_verbose)
{
    print STDERR "Doing copyright tag substitution:\n";
}
unless ($opt_noact)
{
    finddepth(\&expand_tags, "$subdir\_$opt_tag");
}

if ($opt_verbose)
{
    print STDERR "tar cvzf $subdir\_$opt_tag.tar.gz $subdir\_$opt_tag\n";
}
unless ($opt_noact)
{
    `tar cvzf $subdir\_$opt_tag.tar.gz $subdir\_$opt_tag`;
}

# End of main execution.

sub print_usage
{
    print <<EOF;
    $0 usage:
    $0 [-hnv --help --noact --verbose] {--tag=<tag> | -t <tag>} {--dir=<subdir> | -d <subdir>}
EOF
}

sub expand_tags
{
    my ($name) = $_;
    my ($did_subst) = 0;
    my ($ifh, $ofh);

    if (-r $name
	&& (-w $name)
	&& (-f $name)
	&& (-s $name)
	)
    {
	# Okay, we want to do this file.
	# The filename is in $name.
	# The directory is in $File::Find::dir.
	if ($opt_verbose)
	{
	    print STDERR "  $File::Find::dir/$name...";
	}

	$ifh = new FileHandle $name, "r";
	unless (defined $ifh)
	{
	    print STDERR "Error opening $name for reading\n";
	    exit(1);
	}
	$ofh = new FileHandle "$name.tmp", "w";
	unless (defined $ofh)
	{
	    print STDERR "Error opening $name.tmp for writing\n";
	    exit(1);
	}

	while (<$ifh>)
	{
	    if (/^(.*)\<Copyright([ \t]*=[ \t]*([A-Za-z0-9]+))?\>(.*)\n/)
	    {
		$did_subst = 1;
		if (defined($COPYRIGHT{$3, 0}))
		{
		    for ($i = 0; defined($COPYRIGHT{$3, $i}); $i++)
		    {
			print $ofh "$1$COPYRIGHT{$3, $i}$4\n";
		    }
		}
		else
		{
		    for ($i = 0; defined($COPYRIGHT{"jasone", $i}); $i++)
		    {
			print $ofh "$1$COPYRIGHT{\"jasone\", $i}$4\n";
		    }
		}
	    }
	    elsif (/^(.*)\<License\>(.*)\n/)
	    {
		$did_subst = 1;
		foreach (@LICENSE)
		{
		    print $ofh "$1$_$2\n";
		}
	    }
	    elsif (/^(.*)\<Version\>(.*)\n/)
	    {
		$did_subst = 1;
		print $ofh "$1$opt_tag$2\n";
	    }
	    else
	    {
		print $ofh "$_";
	    }
	}
	
	$ifh->close;
	$ofh->close;

	if ($did_subst)
	{
	    `mv $name.tmp $name`;
	}
	else
	{
	    `rm $name.tmp`
	    }

	if ($opt_verbose)
	{
	    if ($did_subst)
	    {
		print STDERR "yes\n";
	    }
	    else
	    {
		print STDERR "no\n";
	    }
	}
    }
    # It seems that this code never gets hit because 'cvs export' doesn't 
    # export empty directories.  
    elsif (-d $name)
    {
	# Try to delete the directory (only succeeds if the directory is empty,
	# which is what we want.
	$rmdir_result = rmdir $name;
	if ($opt_verbose && ($rmdir_result == 1))
	{
	    print STDERR "rmdir $name\n";
	}
    }
}
