Test begin
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
thread_entry_func(): After cnd_wait() call
Test end
