Test begin
qr_new()
  qr_foreach(a): a
  qr_foreach(b): b
  qr_foreach(c): c
  qr_foreach(d): d
  qr_foreach(e): e
  qr_foreach(f): f
  qr_foreach(g): g
  qr_foreach(h): h
  qr_foreach_reverse(a): a
  qr_foreach_reverse(b): b
  qr_foreach_reverse(c): c
  qr_foreach_reverse(d): d
  qr_foreach_reverse(e): e
  qr_foreach_reverse(f): f
  qr_foreach_reverse(g): g
  qr_foreach_reverse(h): h
  qr_next(a): a
  qr_next(b): b
  qr_next(c): c
  qr_next(d): d
  qr_next(e): e
  qr_next(f): f
  qr_next(g): g
  qr_next(h): h
  qr_prev(a): a
  qr_prev(b): b
  qr_prev(c): c
  qr_prev(d): d
  qr_prev(e): e
  qr_prev(f): f
  qr_prev(g): g
  qr_prev(h): h
qr_after_insert()
  qr_foreach(a): a b c d e f g h
  qr_foreach(b): b c d e f g h a
  qr_foreach(c): c d e f g h a b
  qr_foreach(d): d e f g h a b c
  qr_foreach(e): e f g h a b c d
  qr_foreach(f): f g h a b c d e
  qr_foreach(g): g h a b c d e f
  qr_foreach(h): h a b c d e f g
  qr_reverse_foreach(a): h g f e d c b a
  qr_reverse_foreach(b): a h g f e d c b
  qr_reverse_foreach(c): b a h g f e d c
  qr_reverse_foreach(d): c b a h g f e d
  qr_reverse_foreach(e): d c b a h g f e
  qr_reverse_foreach(f): e d c b a h g f
  qr_reverse_foreach(g): f e d c b a h g
  qr_reverse_foreach(h): g f e d c b a h
  qr_next(a): b
  qr_next(b): c
  qr_next(c): d
  qr_next(d): e
  qr_next(e): f
  qr_next(f): g
  qr_next(g): h
  qr_next(h): a
  qr_prev(a): h
  qr_prev(b): a
  qr_prev(c): b
  qr_prev(d): c
  qr_prev(e): d
  qr_prev(f): e
  qr_prev(g): f
  qr_prev(h): g
qr_remove()
  qr_foreach(a): a
  qr_foreach(b): b
  qr_foreach(c): c
  qr_foreach(d): d
  qr_foreach(e): e
  qr_foreach(f): f
  qr_foreach(g): g
  qr_foreach(h): h
  qr_reverse_foreach(a): a
  qr_reverse_foreach(b): b
  qr_reverse_foreach(c): c
  qr_reverse_foreach(d): d
  qr_reverse_foreach(e): e
  qr_reverse_foreach(f): f
  qr_reverse_foreach(g): g
  qr_reverse_foreach(h): h
  qr_next(a): a
  qr_next(b): b
  qr_next(c): c
  qr_next(d): d
  qr_next(e): e
  qr_next(f): f
  qr_next(g): g
  qr_next(h): h
  qr_prev(a): a
  qr_prev(b): b
  qr_prev(c): c
  qr_prev(d): d
  qr_prev(e): e
  qr_prev(f): f
  qr_prev(g): g
  qr_prev(h): h
qr_before_insert()
  qr_foreach(a): a h g f e d c b
  qr_foreach(b): b a h g f e d c
  qr_foreach(c): c b a h g f e d
  qr_foreach(d): d c b a h g f e
  qr_foreach(e): e d c b a h g f
  qr_foreach(f): f e d c b a h g
  qr_foreach(g): g f e d c b a h
  qr_foreach(h): h g f e d c b a
  qr_reverse_foreach(a): b c d e f g h a
  qr_reverse_foreach(b): c d e f g h a b
  qr_reverse_foreach(c): d e f g h a b c
  qr_reverse_foreach(d): e f g h a b c d
  qr_reverse_foreach(e): f g h a b c d e
  qr_reverse_foreach(f): g h a b c d e f
  qr_reverse_foreach(g): h a b c d e f g
  qr_reverse_foreach(h): a b c d e f g h
  qr_next(a): h
  qr_next(b): a
  qr_next(c): b
  qr_next(d): c
  qr_next(e): d
  qr_next(f): e
  qr_next(g): f
  qr_next(h): g
  qr_prev(a): b
  qr_prev(b): c
  qr_prev(c): d
  qr_prev(d): e
  qr_prev(e): f
  qr_prev(f): g
  qr_prev(g): h
  qr_prev(h): a
qr_remove()
  qr_foreach(a): a
  qr_foreach(b): b
  qr_foreach(c): c
  qr_foreach(d): d
  qr_foreach(e): e
  qr_foreach(f): f
  qr_foreach(g): g
  qr_foreach(h): h
  qr_reverse_foreach(a): a
  qr_reverse_foreach(b): b
  qr_reverse_foreach(c): c
  qr_reverse_foreach(d): d
  qr_reverse_foreach(e): e
  qr_reverse_foreach(f): f
  qr_reverse_foreach(g): g
  qr_reverse_foreach(h): h
  qr_next(a): a
  qr_next(b): b
  qr_next(c): c
  qr_next(d): d
  qr_next(e): e
  qr_next(f): f
  qr_next(g): g
  qr_next(h): h
  qr_prev(a): a
  qr_prev(b): b
  qr_prev(c): c
  qr_prev(d): d
  qr_prev(e): e
  qr_prev(f): f
  qr_prev(g): g
  qr_prev(h): h
qr_split(a, e)
  qr_foreach(a): a b c d
  qr_foreach(b): b c d a
  qr_foreach(c): c d a b
  qr_foreach(d): d a b c
  qr_foreach(e): e f g h
  qr_foreach(f): f g h e
  qr_foreach(g): g h e f
  qr_foreach(h): h e f g
qr_meld(a, e)
  qr_foreach(a): a b c d e f g h
  qr_foreach(b): b c d e f g h a
  qr_foreach(c): c d e f g h a b
  qr_foreach(d): d e f g h a b c
  qr_foreach(e): e f g h a b c d
  qr_foreach(f): f g h a b c d e
  qr_foreach(g): g h a b c d e f
  qr_foreach(h): h a b c d e f g
qr_meld(a, e)
  qr_foreach(a): a b c d
  qr_foreach(b): b c d a
  qr_foreach(c): c d a b
  qr_foreach(d): d a b c
  qr_foreach(e): e f g h
  qr_foreach(f): f g h e
  qr_foreach(g): g h e f
  qr_foreach(h): h e f g
qr_split(a, e)
  qr_foreach(a): a b c d e f g h
  qr_foreach(b): b c d e f g h a
  qr_foreach(c): c d e f g h a b
  qr_foreach(d): d e f g h a b c
  qr_foreach(e): e f g h a b c d
  qr_foreach(f): f g h a b c d e
  qr_foreach(g): g h a b c d e f
  qr_foreach(h): h a b c d e f g
qr_split(a, a)
  qr_foreach(a): a b c d e f g h
  qr_foreach(b): b c d e f g h a
  qr_foreach(c): c d e f g h a b
  qr_foreach(d): d e f g h a b c
  qr_foreach(e): e f g h a b c d
  qr_foreach(f): f g h a b c d e
  qr_foreach(g): g h a b c d e f
  qr_foreach(h): h a b c d e f g
qr_meld(a, a)
  qr_foreach(a): a b c d e f g h
  qr_foreach(b): b c d e f g h a
  qr_foreach(c): c d e f g h a b
  qr_foreach(d): d e f g h a b c
  qr_foreach(e): e f g h a b c d
  qr_foreach(f): f g h a b c d e
  qr_foreach(g): g h a b c d e f
  qr_foreach(h): h a b c d e f g
qr_split(a, b)
  qr_foreach(a): a
  qr_foreach(b): b c d e f g h
  qr_foreach(c): c d e f g h b
  qr_foreach(d): d e f g h b c
  qr_foreach(e): e f g h b c d
  qr_foreach(f): f g h b c d e
  qr_foreach(g): g h b c d e f
  qr_foreach(h): h b c d e f g
qr_meld(a, b)
  qr_foreach(a): a b c d e f g h
  qr_foreach(b): b c d e f g h a
  qr_foreach(c): c d e f g h a b
  qr_foreach(d): d e f g h a b c
  qr_foreach(e): e f g h a b c d
  qr_foreach(f): f g h a b c d e
  qr_foreach(g): g h a b c d e f
  qr_foreach(h): h a b c d e f g
Test end
