Test begin
Merging in a list...
Searching for a resource...
simple:value
Testing invalid resources handling...
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_POST_NAME_WHITESPACE, line 1, column 7
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_NAME, line 1, column 5
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_START, line 1, column 1
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_POST_NAME_WHITESPACE, line 1, column 12
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_START, line 1, column 1
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_START, line 1, column 1
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_START, line 1, column 1
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_NAME, line 1, column 5
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_NAME, line 1, column 5
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_NAME, line 1, column 5
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_VALUE_BACKSLASH, line 1, column 12
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_VALUE_BACKSLASH, line 1, column 12
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_VALUE_BACKSLASH, line 1, column 12
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_VALUE_BACKSLASH, line 1, column 12
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_VALUE_BACKSLASH, line 1, column 12
res_p_res_parse(): Illegal character while in _LIBSTASH_RES_STATE_VALUE_BACKSLASH, line 1, column 12
Test end
