Test begin
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 0
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 1
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 2
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 76: main(): _CW_XEPV_FOO
At ./lib/c/libstash/test/c_xep_a.c, line 81: main(): _CW_XEPV_BAR
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 3
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 85: main(): _CW_XEPV_BIZ
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 4
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 5
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 29: func_b(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 33: func_b(): _CW_XEPV_BIZ
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 6
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 44: func_c(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 48: func_c(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 85: main(): _CW_XEPV_BIZ
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
At ./lib/c/libstash/test/c_xep_a.c, line 62: main(): i == 7
At ./lib/c/libstash/test/c_xep_a.c, line 65: main(): _CW_XEPV_CODE
At ./lib/c/libstash/test/c_xep_a.c, line 89: main(): _CW_XEPV_FINALLY
Test end
