#define	ED_ARGUMENT_DIGIT             	  0
#define	ED_CLEAR_SCREEN               	  1
#define	ED_DELETE_NEXT_CHAR           	  2
#define	ED_DELETE_PREV_CHAR           	  3
#define	ED_DELETE_PREV_WORD           	  4
#define	ED_DIGIT                      	  5
#define	ED_END_OF_FILE                	  6
#define	ED_INSERT                     	  7
#define	ED_KILL_LINE                  	  8
#define	ED_MOVE_TO_BEG                	  9
#define	ED_MOVE_TO_END                	 10
#define	ED_NEWLINE                    	 11
#define	ED_NEXT_CHAR                  	 12
#define	ED_NEXT_HISTORY               	 13
#define	ED_NEXT_LINE                  	 14
#define	ED_PREV_CHAR                  	 15
#define	ED_PREV_HISTORY               	 16
#define	ED_PREV_LINE                  	 17
#define	ED_PREV_WORD                  	 18
#define	ED_QUOTED_INSERT              	 19
#define	ED_REDISPLAY                  	 20
#define	ED_SEARCH_NEXT_HISTORY        	 21
#define	ED_SEARCH_PREV_HISTORY        	 22
#define	ED_SEQUENCE_LEAD_IN           	 23
#define	ED_START_OVER                 	 24
#define	ED_TRANSPOSE_CHARS            	 25
#define	ED_TTY_DSUSP                  	 26
#define	ED_TTY_FLUSH_OUTPUT           	 27
#define	ED_TTY_SIGINT                 	 28
#define	ED_TTY_SIGQUIT                	 29
#define	ED_TTY_SIGTSTP                	 30
#define	ED_TTY_START_OUTPUT           	 31
#define	ED_TTY_STOP_OUTPUT            	 32
#define	ED_UNASSIGNED                 	 33
#define	EM_CAPITOL_CASE               	 34
#define	EM_COPY_PREV_WORD             	 35
#define	EM_COPY_REGION                	 36
#define	EM_DELETE_NEXT_WORD           	 37
#define	EM_DELETE_OR_LIST             	 38
#define	EM_EXCHANGE_MARK              	 39
#define	EM_GOSMACS_TRASPOSE           	 40
#define	EM_INC_SEARCH_NEXT            	 41
#define	EM_INC_SEARCH_PREV            	 42
#define	EM_KILL_LINE                  	 43
#define	EM_KILL_REGION                	 44
#define	EM_LOWER_CASE                 	 45
#define	EM_META_NEXT                  	 46
#define	EM_NEXT_WORD                  	 47
#define	EM_SET_MARK                   	 48
#define	EM_TOGGLE_OVERWRITE           	 49
#define	EM_UNIVERSAL_ARGUMENT         	 50
#define	EM_UPPER_CASE                 	 51
#define	EM_YANK                       	 52
#define	VI_ADD                        	 53
#define	VI_ADD_AT_EOL                 	 54
#define	VI_CHANGE_CASE                	 55
#define	VI_CHANGE_META                	 56
#define	VI_CHANGE_TO_EOL              	 57
#define	VI_COMMAND_MODE               	 58
#define	VI_DELETE_META                	 59
#define	VI_DELETE_PREV_CHAR           	 60
#define	VI_END_WORD                   	 61
#define	VI_INSERT                     	 62
#define	VI_INSERT_AT_BOL              	 63
#define	VI_KILL_LINE_PREV             	 64
#define	VI_LIST_OR_EOF                	 65
#define	VI_NEXT_CHAR                  	 66
#define	VI_NEXT_SPACE_WORD            	 67
#define	VI_NEXT_WORD                  	 68
#define	VI_PASTE_NEXT                 	 69
#define	VI_PASTE_PREV                 	 70
#define	VI_PREV_CHAR                  	 71
#define	VI_PREV_SPACE_WORD            	 72
#define	VI_PREV_WORD                  	 73
#define	VI_REPEAT_NEXT_CHAR           	 74
#define	VI_REPEAT_PREV_CHAR           	 75
#define	VI_REPEAT_SEARCH_NEXT         	 76
#define	VI_REPEAT_SEARCH_PREV         	 77
#define	VI_REPLACE_CHAR               	 78
#define	VI_REPLACE_MODE               	 79
#define	VI_SEARCH_NEXT                	 80
#define	VI_SEARCH_PREV                	 81
#define	VI_SUBSTITUTE_CHAR            	 82
#define	VI_SUBSTITUTE_LINE            	 83
#define	VI_TO_END_WORD                	 84
#define	VI_TO_NEXT_CHAR               	 85
#define	VI_TO_PREV_CHAR               	 86
#define	VI_UNDO                       	 87
#define	VI_UNDO_LINE                  	 88
#define	VI_ZERO                       	 89
#define	EL_NUM_FCNS                   	 90
typedef el_action_t (*el_func_t) __P((EditLine *, int));
protected el_func_t* func__get __P((void));
