g_count: 100
Thread 0 about to call lwq_lock()
Thread 1 about to call lwq_lock()
Thread 2 about to call lwq_lock()
Thread 3 about to call lwq_lock()
Thread 4 about to call lwq_lock()
Thread 5 about to call lwq_lock()
Thread 6 about to call lwq_lock()
Thread 7 about to call lwq_lock()
Thread 8 about to call lwq_lock()
Thread 9 about to call lwq_lock()
Thread 10 about to call lwq_lock()
Thread 11 about to call lwq_lock()
Thread 12 about to call lwq_lock()
Thread 13 about to call lwq_lock()
Thread 14 about to call lwq_lock()
Thread 15 about to call lwq_lock()
Thread 16 about to call lwq_lock()
Thread 17 about to call lwq_lock()
Thread 18 about to call lwq_lock()
Thread 19 about to call lwq_lock()
Thread 0 has lock
Thread 1 has lock
Thread 2 has lock
Thread 3 has lock
Thread 4 has lock
Thread 5 has lock
Thread 6 has lock
Thread 7 has lock
Thread 8 has lock
Thread 9 has lock
Thread 10 has lock
Thread 11 has lock
Thread 12 has lock
Thread 13 has lock
Thread 14 has lock
Thread 15 has lock
Thread 16 has lock
Thread 17 has lock
Thread 18 has lock
Thread 19 has lock
