/* -*- mode: c ; c-file-style: "canonware-c-style" -*-
 * This file is automatically generated.
 ******************************************************************************
 *
 * <Copyright = jasone>
 * <License>
 *
 ******************************************************************************
 *
 * Version: Onyx <Version = onyx>
 *
 ******************************************************************************/

#include "libonyx/libonyx.h"

void
nxo_p_thread_nxcode(cw_nxo_t *a_thread)
{
    cw_onyx_code(a_thread, "{dict begin $userdict currentdict dstack dup sbdup dup spop begin pop $threaddict currentdict def def $currenterror < $newerror false $errorname `' $estack stack $istack stack $ostack stack $dstack stack $line 1 $column 0 > def $errordict < $stop $stop load $handleerror {$currenterror load begin stderr nonblocking stderr false setnonblocking $errorname load $syntaxerror eq {stderr dup `At line ' write pop dup $line load cvs write pop dup `, column ' write pop dup $column load cvs write pop `: ' write pop} if stderr dup `Error ' write pop dup $errorname load 1 sprints write pop dup `\nostack: ' write pop dup $ostack load 1 sprints write pop dup `\ndstack: ' write pop dup $dstack load 1 sprints write pop `\n' write pop $estack load scount 1 sub dup 0 gt {stderr dup `estack/istack trace (0..' write pop 1 idup cvs stderr exch write pop `):\n' write pop} if 0 1 dn {dup cvs stderr exch write pop dup $estack load dup dn sidup spop dup type $arraytype eq {`: {\n' stderr exch write pop dup length 1 sub 0 1 dn {2 idup $istack load dup dn sidup spop 1 idup eq {dup < $w 3 > outputs stderr exch write pop `:--> '} {`\t'} ifelse stderr exch write pop 1 idup exch get 1 sprints stderr exch write pop stderr `\n' write pop} for stderr `}\n' write pop pop} {stderr `:\t' write pop 1 sprints stderr exch write pop stderr `\n' write pop} ifelse pop} for stderr exch setnonblocking end flush} bind > def end}eval");
}
