Test begin
ql_new()
  ql_first(): NULL
  ql_last(): NULL
  ql_foreach():
  ql_reverse_foreach():
ql_tail_insert()
  ql_first(): a
  ql_last(): h
  ql_foreach(): a b c d e f g h
  ql_reverse_foreach(): h g f e d c b a
  ql_next(a): b
  ql_next(b): c
  ql_next(c): d
  ql_next(d): e
  ql_next(e): f
  ql_next(f): g
  ql_next(g): h
  ql_next(h): NULL
  ql_prev(h): g
  ql_prev(g): f
  ql_prev(f): e
  ql_prev(e): d
  ql_prev(d): c
  ql_prev(c): b
  ql_prev(b): a
  ql_prev(a): NULL
ql_tail_remove()
  --> Iteration 0
  ql_first(): a
  ql_last(): h
  ql_foreach(): a b c d e f g h
  --> Iteration 1
  ql_first(): a
  ql_last(): g
  ql_foreach(): a b c d e f g
  --> Iteration 2
  ql_first(): a
  ql_last(): f
  ql_foreach(): a b c d e f
  --> Iteration 3
  ql_first(): a
  ql_last(): e
  ql_foreach(): a b c d e
  --> Iteration 4
  ql_first(): a
  ql_last(): d
  ql_foreach(): a b c d
  --> Iteration 5
  ql_first(): a
  ql_last(): c
  ql_foreach(): a b c
  --> Iteration 6
  ql_first(): a
  ql_last(): b
  ql_foreach(): a b
  --> Iteration 7
  ql_first(): a
  ql_last(): a
  ql_foreach(): a
  ql_first(): NULL
  ql_last(): NULL
  ql_foreach():
  ql_reverse_foreach():
ql_head_insert()
  ql_first(): h
  ql_last(): a
  ql_foreach(): h g f e d c b a
  ql_reverse_foreach(): a b c d e f g h
  ql_next(h): g
  ql_next(g): f
  ql_next(f): e
  ql_next(e): d
  ql_next(d): c
  ql_next(c): b
  ql_next(b): a
  ql_next(a): NULL
  ql_prev(a): b
  ql_prev(b): c
  ql_prev(c): d
  ql_prev(d): e
  ql_prev(e): f
  ql_prev(f): g
  ql_prev(g): h
  ql_prev(h): NULL
ql_head_remove()
  --> Iteration 0
  ql_first(): h
  ql_last(): a
  ql_foreach(): h g f e d c b a
  --> Iteration 1
  ql_first(): g
  ql_last(): a
  ql_foreach(): g f e d c b a
  --> Iteration 2
  ql_first(): f
  ql_last(): a
  ql_foreach(): f e d c b a
  --> Iteration 3
  ql_first(): e
  ql_last(): a
  ql_foreach(): e d c b a
  --> Iteration 4
  ql_first(): d
  ql_last(): a
  ql_foreach(): d c b a
  --> Iteration 5
  ql_first(): c
  ql_last(): a
  ql_foreach(): c b a
  --> Iteration 6
  ql_first(): b
  ql_last(): a
  ql_foreach(): b a
  --> Iteration 7
  ql_first(): a
  ql_last(): a
  ql_foreach(): a
  ql_first(): NULL
  ql_last(): NULL
  ql_foreach():
  ql_reverse_foreach():
ql_tail_insert(), ql_before_insert(), ql_after_insert()
  ql_first(): f
  ql_last(): d
  ql_foreach(): f b c g a e h d
  ql_reverse_foreach(): d h e a g c b f
  ql_next(f): b
  ql_next(b): c
  ql_next(c): g
  ql_next(g): a
  ql_next(a): e
  ql_next(e): h
  ql_next(h): d
  ql_next(d): NULL
  ql_prev(d): h
  ql_prev(h): e
  ql_prev(e): a
  ql_prev(a): g
  ql_prev(g): c
  ql_prev(c): b
  ql_prev(b): f
  ql_prev(f): NULL
ql_remove()
  --> Iteration 0
  ql_first(): f
  ql_last(): d
  ql_foreach(): f b c g e h d
  --> Iteration 1
  ql_first(): f
  ql_last(): d
  ql_foreach(): f c g e h d
  --> Iteration 2
  ql_first(): f
  ql_last(): d
  ql_foreach(): f g e h d
  --> Iteration 3
  ql_first(): f
  ql_last(): h
  ql_foreach(): f g e h
  --> Iteration 4
  ql_first(): f
  ql_last(): h
  ql_foreach(): f g h
  --> Iteration 5
  ql_first(): g
  ql_last(): h
  ql_foreach(): g h
  --> Iteration 6
  ql_first(): h
  ql_last(): h
  ql_foreach(): h
  --> Iteration 7
  ql_first(): NULL
  ql_last(): NULL
  ql_foreach():
Test end
